./bkrisc_core_top.v
./data_mem.v
./decode_execute/1control_unit.v
./decode_execute/1tb_control_unit.v
./decode_execute/alu.v
./decode_execute/alu_tb.v
./decode_execute/branch_unit.v
./decode_execute/control_unit.v
./decode_execute/decoder.v
./decode_execute/decode_execute.v
./decode_execute/fftbutterfly.v
./decode_execute/fft_butterfly.v
./decode_execute/forward_unit.v
./decode_execute/hazard_unit.v
./decode_execute/id_ex_reg.v
./decode_execute/imm_gen.v
./decode_execute/regfile.v
./decode_execute/tb_alu.v
./decode_execute/tb_branch_unit.v
./decode_execute/tb_control_unit.v
./decode_execute/tb_decoder.v
./decode_execute/tb_decode_execute.v
./decode_execute/tb_fft_butterfly.v
./decode_execute/tb_forward_unit.v
./decode_execute/tb_hazard_unit.v
./decode_execute/tb_id_ex_reg.v
./decode_execute/tb_imm_gen.v
./decode_execute/tb_regfile.v
./fetch_stage/fetch_stage.v
./fetch_stage/instr_mem.v
./fetch_stage/pc_reg.v
./fetch_stage/tb_fetch_stage.v
./fetch_stage/tb_instr_mem.v
./fetch_stage/tb_pc_reg.v
./id_ex_reg.v
./if_id_reg.v
./mem_wb_stage/mem_wb.v
./mem_wb_stage/mem_wb_reg.v
./mem_wb_stage/tb_mem_wb.v
./mem_wb_stage/tb_wb_mux.v
./mem_wb_stage/wb_mux.v
./risc_core_top.v
./risc_core_top_tb.v
./sim/decode_execute/tb_imm_gen.v
./sim/fetch_stage/tb_fetch_stage_v2.v
./tb_core_top.v
./tb_data_mem.v
./tb_id_ex_reg.v
./tb_if_id_reg.v
./tb_risc_core_top.v
./top1.v
