-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Mon May  4 14:29:33 2026
-- Host        : DESKTOP-6J96HA4 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim C:/Users/user/Documents/RISC_mid1/fetch_stage/fetch_stage_sim_netlist.vhdl
-- Design      : fetch_stage
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
